package projectakhir;

import javax.swing.JOptionPane;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Utama extends javax.swing.JFrame {
    
    File f = new File("C:\\Booking");
    int ln;
    /**
     * Creates new form NewJFrame
     */
    public Utama() {
        initComponents();
    }
    public Utama(String _username) {
        initComponents();
        Utama home = new Utama();
        lblwelcome.setText("Welcome, " +_username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbljudul = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        homebtn = new javax.swing.JToggleButton();
        pnlpemesanan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pembtn = new javax.swing.JToggleButton();
        pnllogout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jpanutama = new javax.swing.JPanel();
        jpanhome = new javax.swing.JPanel();
        radbtngaruda = new javax.swing.JRadioButton();
        radbtnlion = new javax.swing.JRadioButton();
        radbtnsriwijaya = new javax.swing.JRadioButton();
        radbtnbatik = new javax.swing.JRadioButton();
        radbtnairasia = new javax.swing.JRadioButton();
        lbldesmaskapai = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbldismaskapai = new javax.swing.JLabel();
        lbldismaskapai1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jpanpem1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fclassbtn = new javax.swing.JRadioButton();
        eclassbtn = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcboxtujuan = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jpanpem2 = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        pagibtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        siangbtn = new javax.swing.JRadioButton();
        malambtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tiketText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jpanpem3 = new javax.swing.JPanel();
        nextButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblharga = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jcboxmaskapai = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jpanres = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        lbljudul.setBackground(new java.awt.Color(255, 255, 255));
        lbljudul.setFont(new java.awt.Font("Freehand521 BT", 0, 30)); // NOI18N
        lbljudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljudul.setText("HOME");
        lbljudul.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbljudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbljudul, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlhome.setBackground(new java.awt.Color(102, 204, 255));
        pnlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlhomeMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Freehand575 BT", 1, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Home.png"))); // NOI18N
        jLabel2.setText("HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlhomeLayout = new javax.swing.GroupLayout(pnlhome);
        pnlhome.setLayout(pnlhomeLayout);
        pnlhomeLayout.setHorizontalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlhomeLayout.setVerticalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlpemesanan.setBackground(new java.awt.Color(102, 204, 255));
        pnlpemesanan.setPreferredSize(new java.awt.Dimension(110, 72));

        jLabel3.setFont(new java.awt.Font("Freehand575 BT", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/plus.png"))); // NOI18N
        jLabel3.setText("PEMESANAN");

        pembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpemesananLayout = new javax.swing.GroupLayout(pnlpemesanan);
        pnlpemesanan.setLayout(pnlpemesananLayout);
        pnlpemesananLayout.setHorizontalGroup(
            pnlpemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlpemesananLayout.setVerticalGroup(
            pnlpemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpemesananLayout.createSequentialGroup()
                .addGroup(pnlpemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpemesananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpemesananLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnllogout.setBackground(new java.awt.Color(102, 204, 255));
        pnllogout.setPreferredSize(new java.awt.Dimension(110, 72));
        pnllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnllogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnllogoutMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Freehand575 BT", 1, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/logout.png"))); // NOI18N
        jLabel5.setText("LOG OUT");

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnllogoutLayout = new javax.swing.GroupLayout(pnllogout);
        pnllogout.setLayout(pnllogoutLayout);
        pnllogoutLayout.setHorizontalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnllogoutLayout.setVerticalGroup(
            pnllogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnllogoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlpemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
            .addComponent(pnlhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnllogout, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlpemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnllogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));

        lblwelcome.setFont(new java.awt.Font("Forte", 0, 35)); // NOI18N
        lblwelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblwelcome.setText("WELCOME");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(51, 51, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jpanutama.setBackground(new java.awt.Color(153, 204, 255));
        jpanutama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jpanutama.setLayout(new java.awt.CardLayout());

        jpanhome.setBackground(new java.awt.Color(153, 204, 255));

        radbtngaruda.setBackground(new java.awt.Color(153, 204, 255));
        radbtngaruda.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        radbtngaruda.setText("Garuda Indonesia");
        radbtngaruda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radbtngaruda.setPreferredSize(new java.awt.Dimension(105, 20));
        radbtngaruda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtngarudaActionPerformed(evt);
            }
        });

        radbtnlion.setBackground(new java.awt.Color(153, 204, 255));
        radbtnlion.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        radbtnlion.setText("Lion Air");
        radbtnlion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radbtnlion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnlionActionPerformed(evt);
            }
        });

        radbtnsriwijaya.setBackground(new java.awt.Color(153, 204, 255));
        radbtnsriwijaya.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        radbtnsriwijaya.setText("Sriwijaya Air");
        radbtnsriwijaya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radbtnsriwijaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnsriwijayaActionPerformed(evt);
            }
        });

        radbtnbatik.setBackground(new java.awt.Color(153, 204, 255));
        radbtnbatik.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        radbtnbatik.setText("Batik Air");
        radbtnbatik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radbtnbatik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnbatikActionPerformed(evt);
            }
        });

        radbtnairasia.setBackground(new java.awt.Color(153, 204, 255));
        radbtnairasia.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        radbtnairasia.setText("AirAsia Indonesia");
        radbtnairasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnairasiaActionPerformed(evt);
            }
        });

        lbldesmaskapai.setFont(new java.awt.Font("Monotype Corsiva", 2, 15)); // NOI18N
        lbldesmaskapai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldesmaskapai.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setFont(new java.awt.Font("Freehand521 BT", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Maskapai :");

        lbldismaskapai.setFont(new java.awt.Font("Monotype Corsiva", 2, 15)); // NOI18N
        lbldismaskapai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbldismaskapai1.setFont(new java.awt.Font("Monotype Corsiva", 2, 15)); // NOI18N
        lbldismaskapai1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator7.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Freehand521 BT", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LIST");

        jSeparator8.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel16.setFont(new java.awt.Font("Freehand521 BT", 0, 40)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Hayand Airport");

        javax.swing.GroupLayout jpanhomeLayout = new javax.swing.GroupLayout(jpanhome);
        jpanhome.setLayout(jpanhomeLayout);
        jpanhomeLayout.setHorizontalGroup(
            jpanhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbldesmaskapai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbldismaskapai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbldismaskapai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanhomeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(radbtnlion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtngaruda, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtnbatik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radbtnsriwijaya, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanhomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanhomeLayout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanhomeLayout.createSequentialGroup()
                        .addComponent(radbtnairasia)
                        .addGap(170, 170, 170))))
        );
        jpanhomeLayout.setVerticalGroup(
            jpanhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanhomeLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radbtngaruda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnlion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnsriwijaya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnbatik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radbtnairasia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldesmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldismaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldismaskapai1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jpanutama.add(jpanhome, "card5");

        jpanpem1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setFont(new java.awt.Font("Freehand575 BT", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DARI:");

        jLabel4.setFont(new java.awt.Font("Freehand575 BT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TUJUAN:");

        jLabel7.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DKI Jakarta");

        fclassbtn.setBackground(new java.awt.Color(153, 204, 255));
        fclassbtn.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        fclassbtn.setText("First Class");
        fclassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fclassbtnActionPerformed(evt);
            }
        });

        eclassbtn.setBackground(new java.awt.Color(153, 204, 255));
        eclassbtn.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        eclassbtn.setText("Economy Class");
        eclassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eclassbtnActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pointright.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Freehand575 BT", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CLASS:");

        jcboxtujuan.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        jcboxtujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bali", "Makassar", "Kalimantan", "Surabaya", "Sumatera" }));
        jcboxtujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxtujuanActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel1.setFont(new java.awt.Font("Freehand521 BT", 0, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hayand Airport");

        javax.swing.GroupLayout jpanpem1Layout = new javax.swing.GroupLayout(jpanpem1);
        jpanpem1.setLayout(jpanpem1Layout);
        jpanpem1Layout.setHorizontalGroup(
            jpanpem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(jpanpem1Layout.createSequentialGroup()
                .addGroup(jpanpem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpanpem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem1Layout.createSequentialGroup()
                                .addComponent(jcboxtujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem1Layout.createSequentialGroup()
                                .addComponent(fclassbtn)
                                .addGap(40, 40, 40)
                                .addComponent(eclassbtn)
                                .addGap(111, 111, 111)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpanpem1Layout.setVerticalGroup(
            jpanpem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanpem1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboxtujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanpem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fclassbtn)
                    .addComponent(eclassbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpanutama.add(jpanpem1, "card2");

        jpanpem2.setBackground(new java.awt.Color(153, 204, 255));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pointright.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        pagibtn.setBackground(new java.awt.Color(153, 204, 255));
        pagibtn.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        pagibtn.setText("Pagi (07.30 WIB)");
        pagibtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pagibtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("WAKTU KEBERANGKATAN");

        siangbtn.setBackground(new java.awt.Color(153, 204, 255));
        siangbtn.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        siangbtn.setText("SIANG (13.25 WIB)");
        siangbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        siangbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siangbtnActionPerformed(evt);
            }
        });

        malambtn.setBackground(new java.awt.Color(153, 204, 255));
        malambtn.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        malambtn.setText("MALAM (21.40 WIB)");
        malambtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        malambtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        malambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malambtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Freehand521 BT", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("JUMLAH TIKET");

        tiketText.setFont(new java.awt.Font("Freehand575 BT", 0, 20)); // NOI18N
        tiketText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiketText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketTextActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pointleft.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel12.setFont(new java.awt.Font("Freehand521 BT", 0, 40)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Hayand Airport");

        javax.swing.GroupLayout jpanpem2Layout = new javax.swing.GroupLayout(jpanpem2);
        jpanpem2.setLayout(jpanpem2Layout);
        jpanpem2Layout.setHorizontalGroup(
            jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanpem2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpanpem2Layout.createSequentialGroup()
                .addGroup(jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanpem2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanpem2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pagibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siangbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malambtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanpem2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tiketText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        jpanpem2Layout.setVerticalGroup(
            jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanpem2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanpem2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(pagibtn)
                        .addGap(2, 2, 2)
                        .addGroup(jpanpem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpanpem2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(siangbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(malambtn)
                                .addGap(53, 53, 53)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanpem2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(tiketText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton))))
                    .addComponent(jSeparator4)))
        );

        jpanutama.add(jpanpem2, "card3");

        jpanpem3.setBackground(new java.awt.Color(153, 204, 255));

        nextButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pointright.png"))); // NOI18N
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/poindown.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblharga.setFont(new java.awt.Font("Freehand521 BT", 0, 24)); // NOI18N
        lblharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblharga.setText("Rp.");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pointleft.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jcboxmaskapai.setFont(new java.awt.Font("Freehand521 BT", 0, 18)); // NOI18N
        jcboxmaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AirAsia Indonesia", "Garuda Indonesia", "Sriwijaya Air", "Batik Air", "Lion Air" }));
        jcboxmaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxmaskapaiActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(2, 2));

        jLabel13.setFont(new java.awt.Font("Freehand521 BT", 0, 40)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hayand Airport");

        javax.swing.GroupLayout jpanpem3Layout = new javax.swing.GroupLayout(jpanpem3);
        jpanpem3.setLayout(jpanpem3Layout);
        jpanpem3Layout.setHorizontalGroup(
            jpanpem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanpem3Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem3Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(jpanpem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem3Layout.createSequentialGroup()
                        .addComponent(jcboxmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jpanpem3Layout.setVerticalGroup(
            jpanpem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanpem3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jcboxmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblharga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jpanpem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpanutama.add(jpanpem3, "card4");

        jpanres.setBackground(new java.awt.Color(153, 204, 255));

        jLabel17.setFont(new java.awt.Font("Freehand521 BT", 0, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("BOOKINGAN");

        jButton6.setFont(new java.awt.Font("Freehand521 BT", 0, 24)); // NOI18N
        jButton6.setText("Create .txt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanresLayout = new javax.swing.GroupLayout(jpanres);
        jpanres.setLayout(jpanresLayout);
        jpanresLayout.setHorizontalGroup(
            jpanresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpanresLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton6)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jpanresLayout.setVerticalGroup(
            jpanresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanresLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel17)
                .addGap(77, 77, 77)
                .addComponent(jButton6)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jpanutama.add(jpanres, "card6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanutama, javax.swing.GroupLayout.PREFERRED_SIZE, 451, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpanutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSeparator2.setBackground(new java.awt.Color(51, 51, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMouseClicked
    }//GEN-LAST:event_pnllogoutMouseClicked

    private void pnllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnllogoutMousePressed
        LoginView LV = new LoginView();
        LV.setLocationRelativeTo(null);
        LV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnllogoutMousePressed

    private void pnlhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlhomeMousePressed
        
    }//GEN-LAST:event_pnlhomeMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed

    }//GEN-LAST:event_jLabel2MousePressed

    private void pembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembtnActionPerformed
        if(pembtn.isSelected()){
            homebtn.setSelected(false);
            pembtn.setSelected(false);
            jpanutama.removeAll();
            jpanutama.add(jpanpem1);
            jpanutama.revalidate();
            jpanutama.repaint();
            lbljudul.setText("PEMESANAN");
        }
        
    }//GEN-LAST:event_pembtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        //0 = yes, 1 = no, 2 = cancel
        if(input == 0){
            LoginView LV = new LoginView();
            LV.setLocationRelativeTo(null);
            LV.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        if(homebtn.isSelected()){
            homebtn.setSelected(false);
            pembtn.setSelected(false);
            jpanutama.removeAll();
            jpanutama.add(jpanhome);
            jpanutama.revalidate();
            jpanutama.repaint();
            lbljudul.setText("HOME");
        }
    }//GEN-LAST:event_homebtnActionPerformed

    private void fclassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fclassbtnActionPerformed
        if(fclassbtn.isSelected()){
        eclassbtn.setSelected(false);
        }
    }//GEN-LAST:event_fclassbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jpanutama.removeAll();
        jpanutama.add(jpanpem2);
        jpanutama.revalidate();
        jpanutama.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eclassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eclassbtnActionPerformed
        if(eclassbtn.isSelected()){
        fclassbtn.setSelected(false);
        }
    }//GEN-LAST:event_eclassbtnActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        jpanutama.removeAll();
        jpanutama.add(jpanpem3);
        jpanutama.revalidate();
        jpanutama.repaint();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void pagibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibtnActionPerformed
        if(pagibtn.isSelected()){
            malambtn.setSelected(false);
            siangbtn.setSelected(false);
        }
    }//GEN-LAST:event_pagibtnActionPerformed

    private void siangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siangbtnActionPerformed
        if(siangbtn.isSelected()){
            malambtn.setSelected(false);
            pagibtn.setSelected(false);
        }
    }//GEN-LAST:event_siangbtnActionPerformed

    private void malambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malambtnActionPerformed
        if(malambtn.isSelected()){
            pagibtn.setSelected(false);
            siangbtn.setSelected(false);
        }
    }//GEN-LAST:event_malambtnActionPerformed

    private void tiketTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketTextActionPerformed
        float jumlahtiket = Integer.parseInt(tiketText.getText());
    }//GEN-LAST:event_tiketTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jpanutama.removeAll();
        jpanutama.add(jpanpem1);
        jpanutama.revalidate();
        jpanutama.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        jpanutama.removeAll();
        jpanutama.add(jpanres);
        jpanutama.revalidate();
        jpanutama.repaint();
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String jcbox_tujuan = (String) jcboxtujuan.getSelectedItem();
        String jcbox_maskapai = (String) jcboxmaskapai.getSelectedItem();
        String total_;
        float harga = 0;
        float total = 0;
        float jumlahtiket = Float.parseFloat(tiketText.getText());
        switch(jcbox_tujuan){
            case "Bali":
                if(fclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 702000;
                                break;
                            case "Garuda Indonesia":
                                harga = 822000;
                                break;
                            case "Sriwijaya Air":
                                harga = 772000;
                                break;
                            case "Batik Air":
                                harga = 722000;
                                break;
                            case "Lion Air":
                                harga = 892000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 712000;
                                break;
                            case "Garuda Indonesia":
                                harga = 832000;
                                break;
                            case "Sriwijaya Air":
                                harga = 782000;
                                break;
                            case "Batik Air":
                                harga = 732000;
                                break;
                            case "Lion Air":
                                harga = 902000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                else if(eclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 682000;
                                break;
                            case "Garuda Indonesia":
                                harga = 802000;
                                break;
                            case "Sriwijaya Air":
                                harga = 752000;
                                break;
                            case "Batik Air":
                                harga = 702000;
                                break;
                            case "Lion Air":
                                harga = 872000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 692000;
                                break;
                            case "Garuda Indonesia":
                                harga = 812000;
                                break;
                            case "Sriwijaya Air":
                                harga = 762000;
                                break;
                            case "Batik Air":
                                harga = 712000;
                                break;
                            case "Lion Air":
                                harga = 882000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                total = jumlahtiket * harga;
                total_ = Float.toString(total);
                lblharga.setText("Rp. " + total_);
                break;
            case "Makassar":
                if(fclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 731000;
                                break;
                            case "Garuda Indonesia":
                                harga = 851000;
                                break;
                            case "Sriwijaya Air":
                                harga = 801000;
                                break;
                            case "Batik Air":
                                harga = 751000;
                                break;
                            case "Lion Air":
                                harga = 921000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 921000;
                                break;
                            case "Garuda Indonesia":
                                harga = 832000;
                                break;
                            case "Sriwijaya Air":
                                harga = 782000;
                                break;
                            case "Batik Air":
                                harga = 732000;
                                break;
                            case "Lion Air":
                                harga = 902000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                else if(eclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 711000;
                                break;
                            case "Garuda Indonesia":
                                harga = 831000;
                                break;
                            case "Sriwijaya Air":
                                harga = 781000;
                                break;
                            case "Batik Air":
                                harga = 731000;
                                break;
                            case "Lion Air":
                                harga = 901000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 721000;
                                break;
                            case "Garuda Indonesia":
                                harga = 841000;
                                break;
                            case "Sriwijaya Air":
                                harga = 791000;
                                break;
                            case "Batik Air":
                                harga = 741000;
                                break;
                            case "Lion Air":
                                harga = 911000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                total = jumlahtiket * harga;
                total_ = Float.toString(total);
                lblharga.setText("Rp. " + total_);
                break;
            case "Kalimantan":
                if(fclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 765000;
                                break;
                            case "Garuda Indonesia":
                                harga = 885000;
                                break;
                            case "Sriwijaya Air":
                                harga = 835000;
                                break;
                            case "Batik Air":
                                harga = 785000;
                                break;
                            case "Lion Air":
                                harga = 855000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 775000;
                                break;
                            case "Garuda Indonesia":
                                harga = 895000;
                                break;
                            case "Sriwijaya Air":
                                harga = 845000;
                                break;
                            case "Batik Air":
                                harga = 795000;
                                break;
                            case "Lion Air":
                                harga = 865000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                else if(eclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 745000;
                                break;
                            case "Garuda Indonesia":
                                harga = 865000;
                                break;
                            case "Sriwijaya Air":
                                harga = 815000;
                                break;
                            case "Batik Air":
                                harga = 765000;
                                break;
                            case "Lion Air":
                                harga = 835000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 755000;
                                break;
                            case "Garuda Indonesia":
                                harga = 875000;
                                break;
                            case "Sriwijaya Air":
                                harga = 825000;
                                break;
                            case "Batik Air":
                                harga = 775000;
                                break;
                            case "Lion Air":
                                harga = 845000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                total = jumlahtiket * harga;
                total_ = Float.toString(total);
                lblharga.setText("Rp. " + total_);
                break;
            case "Surabaya":
                if(fclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 673000;
                                break;
                            case "Garuda Indonesia":
                                harga = 793000;
                                break;
                            case "Sriwijaya Air":
                                harga = 743000;
                                break;
                            case "Batik Air":
                                harga = 693000;
                                break;
                            case "Lion Air":
                                harga = 763000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 683000;
                                break;
                            case "Garuda Indonesia":
                                harga = 803000;
                                break;
                            case "Sriwijaya Air":
                                harga = 753000;
                                break;
                            case "Batik Air":
                                harga = 703000;
                                break;
                            case "Lion Air":
                                harga = 773000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                else if(eclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 653000;
                                break;
                            case "Garuda Indonesia":
                                harga = 773000;
                                break;
                            case "Sriwijaya Air":
                                harga = 723000;
                                break;
                            case "Batik Air":
                                harga = 673000;
                                break;
                            case "Lion Air":
                                harga = 743000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 663000;
                                break;
                            case "Garuda Indonesia":
                                harga = 783000;
                                break;
                            case "Sriwijaya Air":
                                harga = 733000;
                                break;
                            case "Batik Air":
                                harga = 683000;
                                break;
                            case "Lion Air":
                                harga = 753000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                total = jumlahtiket * harga;
                total_ = Float.toString(total);
                lblharga.setText("Rp. " + total_);
                break;
            case "Sumatera":
                if(fclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 753000;
                                break;
                            case "Garuda Indonesia":
                                harga = 873000;
                                break;
                            case "Sriwijaya Air":
                                harga = 823000;
                                break;
                            case "Batik Air":
                                harga = 773000;
                                break;
                            case "Lion Air":
                                harga = 843000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 763000;
                                break;
                            case "Garuda Indonesia":
                                harga = 883000;
                                break;
                            case "Sriwijaya Air":
                                harga = 833000;
                                break;
                            case "Batik Air":
                                harga = 783000;
                                break;
                            case "Lion Air":
                                harga = 853000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                else if(eclassbtn.isSelected()){
                    if(pagibtn.isSelected() || siangbtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 733000;
                                break;
                            case "Garuda Indonesia":
                                harga = 853000;
                                break;
                            case "Sriwijaya Air":
                                harga = 803000;
                                break;
                            case "Batik Air":
                                harga = 753000;
                                break;
                            case "Lion Air":
                                harga = 823000;
                                break;
                            default:
                                break;
                        }
                    }
                    if(malambtn.isSelected()){
                        switch (jcbox_maskapai) {
                            case "AirAsia Indonesia":
                                harga = 743000;
                                break;
                            case "Garuda Indonesia":
                                harga = 863000;
                                break;
                            case "Sriwijaya Air":
                                harga = 813000;
                                break;
                            case "Batik Air":
                                harga = 763000;
                                break;
                            case "Lion Air":
                                harga = 833000;
                                break;
                            default:
                                break;
                        }
                    }
                }
                total = jumlahtiket * harga;
                total_ = Float.toString(total);
                lblharga.setText("Rp. " + total_);
            default:
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jpanutama.removeAll();
        jpanutama.add(jpanpem2);
        jpanutama.revalidate();
        jpanutama.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radbtngarudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtngarudaActionPerformed
        if(radbtngaruda.isSelected()){
            radbtnlion.setSelected(false);
            radbtnsriwijaya.setSelected(false);
            radbtnbatik.setSelected(false);
            radbtnairasia.setSelected(false);
            lbldesmaskapai.setText("Untuk harga maskapai Garuda Air: Rp. 700.000");
            lbldismaskapai.setText("Diskon 2%");
            lbldismaskapai1.setText("Jika pemesanan tiket kelipatan 3");
        }
    }//GEN-LAST:event_radbtngarudaActionPerformed

    private void radbtnlionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnlionActionPerformed
        if(radbtnlion.isSelected()){
            radbtngaruda.setSelected(false);
            radbtnsriwijaya.setSelected(false);
            radbtnbatik.setSelected(false);
            radbtnairasia.setSelected(false);
            lbldesmaskapai.setText("Untuk harga maskapai Lion Air: Rp. 670.000");
            lbldismaskapai.setText("Diskon 3%");
            lbldismaskapai1.setText("Jika pemesanan tiket kelipatan 4");
        }
    }//GEN-LAST:event_radbtnlionActionPerformed

    private void radbtnsriwijayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnsriwijayaActionPerformed
        if(radbtnsriwijaya.isSelected()){
            radbtngaruda.setSelected(false);
            radbtnlion.setSelected(false);
            radbtnbatik.setSelected(false);
            radbtnairasia.setSelected(false);
            lbldesmaskapai.setText("Untuk harga maskapai Sriwijaya Air: Rp. 650.000");
            lbldismaskapai.setText("Diskon 4%");
            lbldismaskapai1.setText("Jika pemesanan tiket kelipatan 5");
        }
    }//GEN-LAST:event_radbtnsriwijayaActionPerformed

    private void radbtnbatikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnbatikActionPerformed
        if(radbtnbatik.isSelected()){
            radbtngaruda.setSelected(false);
            radbtnlion.setSelected(false);
            radbtnsriwijaya.setSelected(false);
            radbtnairasia.setSelected(false);
            lbldesmaskapai.setText("Untuk harga maskapai Batik Air: Rp. 600.000");
            lbldismaskapai.setText("Diskon 3%");
            lbldismaskapai1.setText("Jika pemesanan tiket kelipatan genap");
        }
    }//GEN-LAST:event_radbtnbatikActionPerformed

    private void radbtnairasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnairasiaActionPerformed
        if(radbtnairasia.isSelected()){
            radbtngaruda.setSelected(false);
            radbtnlion.setSelected(false);
            radbtnsriwijaya.setSelected(false);
            radbtnbatik.setSelected(false);
            lbldesmaskapai.setText("Untuk harga maskapai AirAsia Indonesia: Rp. 580.000");
            lbldismaskapai.setText("Diskon 3%");
            lbldismaskapai1.setText("Jika pemesanan tiket kelipatan ganjil");
        }
    }//GEN-LAST:event_radbtnairasiaActionPerformed

    private void jcboxtujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxtujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboxtujuanActionPerformed

    private void jcboxmaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxmaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboxmaskapaiActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String jcbox_tujuan = (String) jcboxtujuan.getSelectedItem();
        String jcbox_maskapai = (String) jcboxmaskapai.getSelectedItem();
        Float jumlahtiket = Float.parseFloat(tiketText.getText());
        String class_ = null;
        String jam = null;
        if(!f.exists()){
            f.mkdirs();
        }
        try {
            RandomAccessFile raf = new RandomAccessFile(f+"\\Booking.txt", "rw");
            FileReader fr = new FileReader(f+"\\Booking.txt");
            System.out.println("file exists!");
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            //if condition added after video to have no lines on first entry
            if(ln>0){
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            }
            if(fclassbtn.isSelected()){
                if(pagibtn.isSelected()){
                    class_ = "First Class";
                    jam = "Pagi(07.30 WIB)";
                }
                else if(siangbtn.isSelected()){
                    class_ = "First Class";
                    jam = "Siang(13.25 WIB)";
                }
                else if(malambtn.isSelected()){
                    class_ = "First Class";
                    jam = "Malam(21.40 WIB)";
                }
            }
            else if(eclassbtn.isSelected()){
                if(pagibtn.isSelected()){
                    class_ = "First Class";
                    jam = "Pagi(07.30 WIB)";
                }
                else if(siangbtn.isSelected()){
                    class_ = "First Class";
                    jam = "Siang(13.25 WIB)";
                }
                else if(malambtn.isSelected()){
                    class_ = "First Class";
                    jam = "Malam(21.40 WIB)";
                }
            }
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            for(int h = 1; h <= jumlahtiket; h++){
                raf.writeBytes("--------------------------------------------------"+ "\r\n");
                raf.writeBytes(class_ +"\r\n");
                raf.writeBytes("Tujuan: "+ jcbox_tujuan+ "\r\n");    
                raf.writeBytes("Waktu Keberangkatan : "+ jam +"\r\n");
                raf.writeBytes("Maskapai: "+ jcbox_maskapai +"\r\n");
                raf.writeBytes("Kode Bangku: "+ "#KBHDAT-"+ h +"\r\n");
            }
            raf.writeBytes("--------------------------------------------------"+ "\r\n");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter fw = new FileWriter(f+"\\logins.txt");
                System.out.println("File created");
            } catch (IOException ex1) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } catch (IOException ex) {
            Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Tiket sudah terbuat!");
        LoginView LV = new LoginView();
        LV.setVisible(true);
        LV.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton eclassbtn;
    private javax.swing.JRadioButton fclassbtn;
    private javax.swing.JToggleButton homebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jcboxmaskapai;
    private javax.swing.JComboBox<String> jcboxtujuan;
    private javax.swing.JPanel jpanhome;
    private javax.swing.JPanel jpanpem1;
    private javax.swing.JPanel jpanpem2;
    private javax.swing.JPanel jpanpem3;
    private javax.swing.JPanel jpanres;
    private javax.swing.JPanel jpanutama;
    private javax.swing.JLabel lbldesmaskapai;
    private javax.swing.JLabel lbldismaskapai;
    private javax.swing.JLabel lbldismaskapai1;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbljudul;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JRadioButton malambtn;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton1;
    private javax.swing.JRadioButton pagibtn;
    private javax.swing.JToggleButton pembtn;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnllogout;
    private javax.swing.JPanel pnlpemesanan;
    private javax.swing.JRadioButton radbtnairasia;
    private javax.swing.JRadioButton radbtnbatik;
    private javax.swing.JRadioButton radbtngaruda;
    private javax.swing.JRadioButton radbtnlion;
    private javax.swing.JRadioButton radbtnsriwijaya;
    private javax.swing.JRadioButton siangbtn;
    private javax.swing.JTextField tiketText;
    // End of variables declaration//GEN-END:variables
}
